* TODO Option to put subtext next to main text

  Compatible with aligned subtext, like this:
  
  DeleteAllFiles /function/      Deletes all your files.
  Quit /function/                Get up and leave. 

* TODO Cycle alternative subtexts  
  Allow to specify multiple alternate subtexts, and supply a command to cycle through them.

* TODO Refine substring/flex matching
  - If the first character of a flex match is also the first character of the item, show that item before items with
    substring (not prefix) matching. The longer the match at the start, the higher the score.
  - The same at the end of string. Useful when choosing filenames with paths.

* TODO Searching in the subtext
  Maybe on the detail text too? probably not.
  
* TODO Allow caller to set arbitrary keys to arbitrary commands during selection. Show what those keys are.

* TODO The variable alien-sel-returned-index
  is computed by searching for the selected item (including properties) inside the list. This is bad beacuse we add
  properties to items along the way.
  The solution is to add a propertiy with the index at the start.
  
  

  
